model_configs:
- model_config: TumbaFluxnet
  fetch_from:
    git:
      url: https://github.com/SeanBryan51/cable_TumbaFluxnet_example
      ref: main
  run_script: ${MODEL_CONFIG_ROOT}/run.sh
  env:
    # CABLE_INPUTS is designed to be set on a per user basis and is required so
    # that input files are discoverable. See
    # https://github.com/SeanBryan51/cable_TumbaFluxnet_example/blob/main/config.sh
    export: [CABLE_INPUTS]
    set:
      # This is required to set the CABLE executable for this model
      # configuration. Note the hard-coded path is a temporary hack and should
      # instead be set to ${MODEL_PREFIX_PATH}/cable where MODEL_PREFIX_PATH is
      # a variable defined by benchcab:
      CABLE_EXE: /Users/seanbryan/dev_local/cable/bin/cable
